# Generated by Django 6.0.5 on 2026-05-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='memebers',
            new_name='members',
        ),
    ]
